MemoBlend/MemoBlend4J

.github/workflows/blank.yml
- テストとして、github Actions のymlファイルを作成しました
=> github Actions のymlファイルを作成

architecture/backend/index.drawio
- backend フォルダーの直下に Java を用いたクリーンアーキテクチャのフォルダ構成を追加しました。
=> backendを中心に素案の策定

src/backend/.gitignore
- .gitignoreの編集
- setting_local.py → config/settings_local.py に変更
- なし。
- https://qiita.com/anqooqie/items/110957797b3d5280c44f
=> gitignoreの編集

.github/dependabot.yml
- フロントエンドとバックエンドに関するdependabotの設定ファイルを追加しました。
- 特になし。
- 特になし。
=> dependabot.ymlを作成

.github/dependabot.yml
- dependabotの検知ディレクトリを適切な場所に修正しました。
- 特になし。
- 特になし。
=> dependabotの検知場所を適切なディレクトリに修正

src/backend/README.md
- pipenvを用いた動作環境の構築方法をbackend\README.mdに追記。
- 特になし。
- https://qiita.com/y-tsutsu/items/54c10e0b2c6b565c887a
=> Pipfileを用いた環境作成をREADME.mdに追記

.github/dependabot.yml
- dependabot.ymlファイルでラベルを追加しました。
特になし。
特になし。
=> depenedabot.ymlにラベルの設定を追加

src/spring-backend/application-core/.gitattributes, src/spring-backend/application-core/.gitignore, src/spring-backend/infrastructure/.gitattributes, src/spring-backend/infrastructure/.gitignore, src/spring-backend/system-common/.gitattributes, src/spring-backend/system-common/.gitignore, src/spring-backend/web/.gitattributes, src/spring-backend/web/.gitignore
- spring-backendサブシステムにおいて、誤って削除したgitignoreとgitattributeを追加する
- 特になし。
- 特になし。
=> gitignoreとgitattributesを追加

src/spring-backend/api-docs/web/api-specification.json, src/spring-backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, src/spring-backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml, src/spring-backend/infrastructure/src/main/resources/data.sql, src/spring-backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java, src/spring-backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetDiariesResponse.java, src/spring-backend/web/src/main/java/com/memoblend/web/controller/dto/util/DataTransferObjectConverter.java
- 日記の全件取得機能を追加しました。
- 特になし。
- #85
=> 日記の全件取得機能を追加

src/spring-backend/api-docs/web/api-specification.json, src/spring-backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java, src/spring-backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.java, src/spring-backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml, src/spring-backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetDiaryResponse.java, src/spring-backend/web/src/main/java/com/memoblend/web/controller/dto/diary/PostDiaryRequest.java, src/spring-backend/web/src/main/java/com/memoblend/web/controller/dto/util/DataTransferObjectConverter.java
- インフラ層ととリポジトリインターフェースに日記の作成、追加、削除機能を実装
- その他、変数名などに軽微な修正を追加しました。
- 日記の作成、追加、削除機能についてアプリケーションサービスや、プレゼンテーション層の実装は行なっていません。
- #94 
- #70 
- #72 
- #73
=> インフラ層ととリポジトリインターフェースに日記の作成、追加、削除機能を実装

src/spring-backend/web/src/main/java/com/memoblend/web/controller/advice/ExceptionHandlerControllerAdvice.java, src/spring-backend/web/src/main/java/com/memoblend/web/controller/advice/LocalExceptionHandlerControllerAdvice.java
- プレゼンテーション層に集約例外ハンドラーを追加しました。
特になし
- #82
=> 集約例外ハンドラーを追加

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java, backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java
- 日記の削除機能を追加しました。
- 削除対象の日記が見つからない場合の例外以外の例外は実装していません。
- #72
=> 日記の削除機能を追加

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/UserApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/Diary.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserNotFoundException.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserRepository.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisUserRepository.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml, backend/web/src/main/java/com/memoblend/web/controller/UserController.java, backend/web/src/main/java/com/memoblend/web/controller/dto/mapper/GetUserReponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/dto/mapper/GetUsersResponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/dto/mapper/PostUserRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/dto/mapper/PutUserRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/dto/user/GetUsersResponse.java, backend/web/src/main/java/com/memoblend/web/controller/dto/user/PostUserRequest.java, backend/web/src/main/java/com/memoblend/web/controller/dto/user/PutUserRequest.java
- ユーザーの全件取得の実装。
- ユーザーIDに合致するユーザーの取得の実装。
- ユーザーのPOST機能の実装。
- ユーザーに関するインフラ層作成（妥当かを入念に確認してください）。
- ユーザーのPOST機能は実装したが試していないです。
- xmlファイルのDELETEのparameterTypeをlong型に変換
=> ユーザーのGETとPOST機能追加

.github/dependabot.yml
- dependabotの設定ファイルが間違っていたので修正します。
- 特になし。
- 特になし。
=> dependabotの設定ファイルを修正

backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.java
- 日記のアプリケーションサービスクラスの単体テストを追加しました。
- 日記のドメインサービスの単体テストを追加しました。
- ユーザーのアプリケーションサービスおよびドメインサービスの単体テストは作成していません。
- #93
=> アプリケーションコア層に単体テストを追加する

backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
- 日記の結合テストを自動化しました。
- ユーザーについては対応していません。
- #143
=> 日記の結合テストを自動化

.github/ISSUE_TEMPLATE/config.yml
- Issueのconfigファイルを追加しました。
特になし。
- #146
=> issueのconfigファイルを追加

.github/ISSUE_TEMPLATE/Issue_template.md, .github/ISSUE_TEMPLATE/config.yml
- Issueの設定を変更しました。
特になし。
- #146
=> Issueテンプレートの設定を変更

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/UserApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java, backend/application-core/src/main/java/com/memoblend/applicationcore/constant/MessageIdConstants.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserAlreadyExistException.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserDomainService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserNotFoundException.java, backend/application-core/src/main/resources/applicationcore/messages.properties, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.java, backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java, backend/web/src/main/java/com/memoblend/web/controller/UserController.java
- ユーザーのアプリケーションログの出力内容変更
- なし
- なし
=> ユーザーのアプリケーションログの出力内容変更

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisUserRepository.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml, backend/infrastructure/src/main/resources/data.sql, backend/infrastructure/src/main/resources/schema.sql, backend/web/src/main/java/com/memoblend/web/controller/dto/user/GetUserResponse.java, backend/web/src/main/java/com/memoblend/web/controller/dto/user/PostUserRequest.java, backend/web/src/main/java/com/memoblend/web/controller/dto/user/PutUserRequest.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUserReponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
- ユーザーの名前のカラム名の変更
- "userName"を"name"、"UserName"を"Name"、"user_name"を"name"に変更
- なし
- なし
=> ユーザーの名前のカラム名の変更

backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java
- UserAplicationServiseの単体テストの実装
- なし
- #163
=> UserAplicationServiseの単体テストの実装

backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java
- 日記のドメインサービステストから不要な記述を削除しました。
- ユーザーについては下記Issueで対応しています。
- #164 
- #174
=> 日記のドメインサービステストから不要な記述を削除

backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java
- UserDomainServiseの単体テストの実装
- なし
- #164
=> UserDomainServiseの単体テストの実装

backend/api-docs/web/api-specification.json, backend/web/src/main/java/com/memoblend/web/controller/UserController.java
- UserControllerの全件取得機能の削除
- UserController以外では全件取得機能の削除を行っていません。
- #171
=> ユーザーの全件取得機能の削除

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
- ユーザードメインの単体テスト実装
- IDのNullチェックテスト
- #205
=> ユーザードメインの単体テスト実装

frontend/diary/src/main.ts, frontend/diary/src/router/index.ts, frontend/diary/src/shared/error-handler/custom-error-handler.ts, frontend/diary/src/shared/error-handler/custom-error.ts, frontend/diary/src/shared/error-handler/global-error-handler.ts, frontend/diary/src/shared/error-handler/injection-symbols.ts, frontend/diary/src/shared/error-handler/use-custom-error-handler.ts, frontend/diary/src/views/diary/DiariesView.vue, frontend/diary/src/views/diary/DiaryCreateView.vue, frontend/diary/src/views/diary/DiaryDetailView.vue, frontend/diary/src/views/diary/DiaryEditView.vue, frontend/diary/src/views/error/ErrorView.vue
- グローバルエラーハンドラを追加しました。
- カスタムエラーハンドラを追加しました。
- そのほか軽微な修正を行いました。
- トーストの追加は行なっていません。
- #213
=> 例外の捕捉環境を整える

frontend/diary/src/App.vue
- メニューバーを有効化しました。
- メニューバーにホームへのリンクと分析画面へのリンクを追加しました。
- 分析画面は追加せず、ダミーのURLを入れています。
- #254
=> メニューバーの有効化

frontend/diary/src/App.vue, frontend/diary/src/components/organisms/LoadingSpinnerOverlay/LoadingSpinnerOverlay.vue, frontend/diary/src/components/organisms/LoadingSpinnerOverlay/index.ts, frontend/diary/src/views/diary/DiariesView.vue, frontend/diary/src/views/diary/DiaryDetailView.vue, frontend/diary/src/views/diary/DiaryEditView.vue
- スピナーコンポーネントの追加
- 各ページにスピナーを実装
- 共通処理としてスピナーを実装していません
- #247
=> apiコール中にスピナーを表示したい

backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.xml
- UserMapperのfindAllとfindByIdを論理削除仕様に修正
- なし
- #258
=> userMapperを論理削除仕様に修正

backend/application-core/src/main/java/com/memoblend/applicationcore/constant/ExceptionIdConstants.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java, backend/application-core/src/main/resources/applicationcore/messages.properties, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
- User.javaとUserTest.javaに対して、定数管理対応を行いました。
- 問題がなければDiaryも同様な方法で定数管理対応を行います。
- なし
- #208
=> Userエンティティの定数管理対応

backend/build.gradle, backend/dependencies.gradle
- 試しにgradleの設定ファイルを修正しました。
- 特になし。
- #277
=> gradleの設定ファイルを微修正

backend/dependencies.gradle
- dependencies.gradleを修正しました・
- 特になし
- #277
=> gradle version catalogの導入を検討する

frontend/diary/src/components/molecules/EventList/EventList.vue
- _definePropsに関する不要なimportを削除しました。
- 特になし。
- #307
=> 不要なimportを削除

backend/dependencies.gradle
- SpotBugsのツールバージョンが間違っていたので修正しました。
- 特になし。
- #313
=> SpotBugsのツールバージョン

frontend/diary/src/generated/api-client/api/user-api.ts, frontend/diary/src/generated/api-client/models/diary.ts, frontend/diary/src/generated/api-client/models/get-diary-response.ts, frontend/diary/src/generated/api-client/models/post-diary-request.ts, frontend/diary/src/generated/api-client/models/put-diary-request.ts, frontend/diary/src/main.ts, frontend/diary/src/views/diary/DiariesView.vue, frontend/diary/src/views/diary/DiaryCreateView.vue
- フロントエンドでたまに発生するエラーが起きないように修正しました。
- 特になし。
- #321
=> フロントエンドで発生している警告に対応

backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/UserApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/CreatedDate.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Id.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/IsDeleted.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Title.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/UserId.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/User.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Id.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/IsDeleted.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/UserMapper.java, frontend/diary/src/generated/api-client/api/user-api.ts, frontend/diary/src/generated/api-client/models/diary.ts, frontend/diary/src/generated/api-client/models/get-diary-response.ts, frontend/diary/src/generated/api-client/models/post-diary-request.ts, frontend/diary/src/generated/api-client/models/put-diary-request.ts
- JavaDocコメントの体裁を統一しました。
- クライアントコードを再生成しました。
- 特になし。
- #316
=> javadocコメントの体裁を統一

.github/release.yml
- リリースノートのテンプレートファイルを追加しました。
- 特になし
- 特になし
=> リリースノートのテンプレートを追加

README.md
- READMEのソフトウェアバージョンを更新しました。
- 特になし
- 特になし
=> READMEのソフトウェアバージョンを更新

analysisapi/analysisapi/ai_processor/diary_analyzer.py, analysisapi/analysisapi/cli.py
- LLMを用いた基盤コード作成しました。
- 具体的には、日記を１つ投げたら、その日記に対する感想を返す機能です。
- なし
- なし
=> LLMを用いた基盤コード作成

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/constant/MessageIdConstants.java, backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryRepository.java, backend/application-core/src/main/resources/applicationcore/messages.properties, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/mapper/DiaryMapper.xml, backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java, backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java, frontend/diary/src/generated/api-client/api/diary-api.ts
- ログインしているユーザーの日記のリストを取得する機能を追加しました。
- アプリケーションコア層およびプレゼンテーション層のテストは追加していません。
- #219
=> ログインしているユーザーの日記のリストを取得する機能を追加

backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java
- 日記のユーザーごとの一覧取得のテストを追加しました。
- 特になし。
- #356
=> 日記のユーザーごとの一覧取得のテストを追加

README.md
- GitDiagramを利用してアーキテクチャの概要図を生成し、READMEに追加しました。
- 特になし。
- 特になし。
=> GitDiagramを利用してアーキテクチャの概要図を生成し、READMEに追加

analysisapi/api-docs/analysisapi/api-specification.json, analysisapi/generateopenapi/cli.py
- OpenAPI出力の修正
- 具体的には、文字化けの修正を行いました。
- なし
- #372
=> OpenAPI出力の修正

.github/ISSUE_TEMPLATE/config.yml
=> Blank Issueの作成を禁止

backend/web/src/main/java/com/memoblend/web/auth/UserStoreImpl.java
- SonarQubeの指摘対応として、Collectors.toList()をStream.toList()に置き換えました
なし
- #411
=> Collectors.toList()をStream.toList()に置換

backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
複数回同じリテラルを呼び出さないよう修正しました
なし
- #406
=> 複数回同じリテラルを呼び出さないよう修正

backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisDiaryRepository.java, backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/MyBatisUserRepository.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiariesResponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/GetDiaryReponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PostDiaryRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/diary/PutDiaryRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUserReponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/GetUsersResponseMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PostUserRequestMapper.java, backend/web/src/main/java/com/memoblend/web/controller/mapper/user/PutUserRequestMapper.java
=> 不要な一時変数を削除

backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/UserApplicationServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryDomainServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserDomainServiceTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java, backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java, backend/web/src/test/java/com/memoblend/web/controller/DiaryControllerTest.java, backend/web/src/test/java/com/memoblend/web/controller/UserControllerTest.java
テストクラスの不要な修飾子を削除しました。
なし
- #407
=> テストクラスの不要な修飾子を削除

backend/application-core/src/test/java/com/memoblend/applicationcore/diary/DiaryTest.java, backend/application-core/src/test/java/com/memoblend/applicationcore/user/UserTest.java
一部のテストをパラメタライズテストに置換しました。
なし
- #408
=> 一部のテストをパラメタライズテストに置換

backend/application-core/src/main/java/com/memoblend/applicationcore/diary/DiaryDomainService.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/UserDomainService.java
=> bool値の返却を条件式に置換

backend/web/src/main/java/com/memoblend/web/controller/util/ProblemDetailsFactory.java
=> 二重括弧の初期化は使用しないよう修正

backend/infrastructure/src/main/java/com/memoblend/infrastructure/repository/config/MyBatisConfig.java
一部の匿名内部クラスをラムダ式に置換しました。
なし
- #409
=> 一部の匿名内部クラスをラムダ式に置換

backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java
=> 空のメソッドにコメントを追加

backend/system-common/src/main/java/com/memoblend/systemcommon/constant/SystemPropertyConstants.java
プライベートコンストラクタの対応漏れに対応しました。
なし
- #404
=> プライベートコンストラクタの対応漏れに対応

backend/system-common/src/main/java/com/memoblend/systemcommon/exception/LogicException.java, backend/system-common/src/main/java/com/memoblend/systemcommon/exception/SystemException.java
一部のフィールドをfinal化しました。
なし
- #410
=> 一部のフィールドをfinal化

backend/application-core/src/main/java/com/memoblend/applicationcore/diary/valueobject/Content.java, backend/application-core/src/main/java/com/memoblend/applicationcore/user/valueobject/Name.java
=> 定数名の命名規則を修正

backend/web/src/main/java/com/memoblend/web/log/ErrorMessageBuilder.java
=> 不要な型キャストを削除

backend/web/src/main/java/com/memoblend/web/controller/util/ProblemDetailsFactory.java
filter().findFirst().isPresent()をanyMatch()に置換しました
なし
- #431
=> filter().findFirst().isPresent()をanyMatch()に置換

backend/web/src/test/java/com/memoblend/web/WebApplicationTests.java
=> 空のメソッドへの追加対応

.github/dependabot.yml
=> dependabotの上限を変更

.github/dependabot.yml
Dependabot Updateの最大数を追加しました。
なし
なし
=> Dependabot Updateの最大数を追加

analysisapi/.vscode/extensions.json, analysisapi/.vscode/settings.json
- 静的解析ツールを導入するために、settings.jsonとextensions.jsonを追加しました。
なし
- #489
=> extension.jsonとsettings.jsonの追加

backend/web/src/main/java/com/memoblend/web/auth/UserStoreImpl.java, backend/web/src/main/java/com/memoblend/web/filter/DummyUserInjectionFilter.java, backend/web/src/main/java/com/memoblend/web/log/ErrorMessageBuilder.java, backend/web/src/main/java/com/memoblend/web/security/WebSecurityConfig.java
Javaプログラムのリファクタリングを実施しました。
なし
- #387
=> Javaプログラムのリファクタリングを実施

analysisapi/app.py, analysisapi/applicationcore/client_application_service.py, analysisapi/applicationcore/collection_load_failed_exception.py, analysisapi/applicationcore/diary_application_service.py, analysisapi/applicationcore/prompt_constants.py, analysisapi/generateopenapi/constants.py, analysisapi/infrastructure/client/client_constants.py, analysisapi/infrastructure/client/client_openai.py, analysisapi/infrastructure/client/client_weather.py, analysisapi/infrastructure/diary_repository.py, analysisapi/infrastructure/infrastructure_constants.py, analysisapi/presentation/controller.py, analysisapi/presentation/exception_handler.py, analysisapi/presentation/exception_handlers.py, analysisapi/presentation/presentation_constants.py, analysisapi/requirements.txt, analysisapi/systemcommon/business_exception.py, analysisapi/systemcommon/logger_config.py, analysisapi/systemcommon/system_exception.py
- 業務例外の共通クラスを作成しました
- システム例外クラスを作成しました
- 共通例外ハンドラーを作成しました
なし
- #483
=> 業務例外の共通クラスを作成

backend/dependencies.gradle, backend/web/build.gradle, backend/web/src/main/resources/application-dev.properties
- SpringBootアプリケーションの開発者体験を向上させることができる、SpringDevToolsの利用を検討しました。
- ホットリロード機能が有用であると感じたため、導入しました。
- カスタムタスクは追加していません
- #557 
1. `./gradlew web:bootRunDev`でバックエンドを起動して下さい
2. 別プロセスで`./gradlew compileJava --continuous`を走らせ自動コンパイルタスクを起動して下さい。
3. UserController.javaに以下のエンドポイントを追加してください
```java
/**
* ホットリロード確認用エンドポイント。
*/
@GetMapping("/ping")
public ResponseEntity<String> ping() {
return ResponseEntity.ok("pong");
}
```
4. `http://localhost:8080/api/user/ping`にアクセスし "pong" が返ることを確認してください。
=> spring dev toolsの利用を検討する

.github/release.yml
- リリースノートテンプレートの不適当に対応しました
なし
- #573 
1. 差分を見て適切に変更されているか再査して下さい
=> リリースノートテンプレートの不適当に対応

analysisapi/presentation/controller.py, analysisapi/presentation/presentation_constants.py
- 不要なURL定義を削除しました
- 不具合に対応しました
なし
- #556 
1. `./gradlew web:bootrundev`でバックエンドを起動します
2. `analysisapi`ディレクトリで`python app.py`でAI分析を起動します
3. localhost:8000/api/diary/1/1にアクセスして正常にベクトルDBにデータが追加されることを確認して下さい
4. localhost:8000/api/schedule/1にアクセスして、予定の提案が正常に実施されることを確認して下さい
=> 日記の月ごと取得の分析aiの修正をしたい

backend/api-docs/web/api-specification.json, backend/application-core/src/main/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationService.java, backend/application-core/src/test/java/com/memoblend/applicationcore/applicationservice/DiaryApplicationServiceTest.java, backend/web/src/main/java/com/memoblend/web/controller/DiaryController.java, backend/web/src/main/java/com/memoblend/web/controller/dto/diary/GetRecommendedScheduleResponse.java, frontend/diary/src/generated/api-client/models/get-recommended-schedule-response.ts, frontend/diary/src/generated/api-client/models/problem-detail.ts, frontend/diary/src/views/schedule/ScheduleSuggestView.vue
- 日記の提案画面をJsonに対応しました
なし
- #624 
1. npm run dev:diary、python app.py 、./gradlew web:bootrundevでそれぞれを起動します
2. http://localhost:5173/schedule/suggestにアクセスする
=> 日記の提案画面を作成する
